jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }} # Use the secret as an environment variable
        run: python app2.py
  